### ISSUE TITLE
Breaking Blocks causes Ghost Blocks

### ISSUE THREAD

**Issue by medtryx** [bloop428/Excavation#15] opened 2020-08-08 09:19 UTC
With Excavation 1.4 installed breaking blocks even without activating the Excavation key is quite often not dropping the block and leaving a ghost block that returns to what it was when you update the block space or try to place something there as well. 

This happened using a diamond pickaxe, Did a small amount of testing and discovered: Breaking ore or sandstone was fine. Breaking an anvil, leaves, or glass panes caused the issue.  I had first noticed an issue with mekanism pipes and assumed that was a Mekanism issue, until I tested just Forge and Mekanism and discovered the issue was not present. Adding only Excavation to the pack caused the issue.  Excavation 1.3b does not cause this issue.

**Comment by bloop428** [comment] 2020-08-08 16:30
Were you on a server? I can't reproduce this on singleplayer

**Comment by medtryx** [comment] 2020-08-08 18:41
I can reproduce this every time I launch the game. I just did further testing, breaking any block in creative mode seems to cause the issue.  In survival breaking anything that can be broken by hand, such as a wood log, even if you do saw with an Axe cause the issue. Breaking dirt with a shovel did not cause the issue, breaking it by hand did cause the issue.  Breaking leaves  by hand causes the issue, with shears there is no issue. 


I normally play with the GDLauncher, however I setup a profile in the Twitch launcher and reproduced the issue. [Here is the crash report for that. ](https://pastebin.com/jym3ZRDq)

**Comment by medtryx** [comment] 2020-08-08 20:36
Here's a [short video of this happening](https://www.youtube.com/watch?v=X7osEIlkq-M). It also ends with a crash after I press the grave key.

**Comment by bloop428** [comment] 2020-08-09 02:46
This should be fixed now. I had some typos and I kinda feel like an idiot

**Closed by bloop428** 2020-08-09 02:46 UTC
Labels: bug, unkown

**Comment by medtryx** [comment] 2020-08-09 02:55
> 
> 
> This should be fixed now. I had some typos and I kinda feel like an idiot

Just updated and tested on my install, working flawlessly! Thanks for the quick updates!
